# Generated by Django 3.2.6 on 2021-08-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0132_product_created_at'),
        ('product', '0147_auto_20210817_1015'),
    ]

    operations = [
    ]
