# Generated by Django 3.1.2 on 2021-03-11 13:06

from django.db import migrations
from ..utils import read_sql_from_file


class Migration(migrations.Migration):
    dependencies = [
        ("salingo", "0001_sku_to_date")
    ]

    operations = [
        migrations.RunSQL(read_sql_from_file('update_prices.sql'))
    ]
