# Generated by Django 3.1.2 on 2021-07-06 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0131_update_ts_vector_existing_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0011_auto_20200714_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('GRN', 'Goods_received_note'), ('GIN', 'Goods_issued_note'), ('IWM', 'Internal warehouse movement'), ('FGTN', 'Finished goods transfer note'), ('IO', 'Internal outgoings')], max_length=10)),
                ('deliverer', models.JSONField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('DRAFT', 'DRAFT')], default='DRAFT', max_length=20)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wms_created_by', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wms_recipient', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='warehouse.warehouse')),
                ('warehouse_second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='warehouse.warehouse')),
            ],
            options={
                'permissions': (('manage_wms', 'Manage wms.'),),
            },
        ),
        migrations.CreateModel(
            name='WmsDocPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wms_doc_position', to='wms.wmsdocument')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wms_doc_position', to='product.productvariant')),
            ],
        ),
    ]
