# Generated by Django 3.1.2 on 2021-07-07 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import saleor.account.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsDeliverer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('postal_code', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=256)),
                ('vat_id', models.CharField(blank=True, max_length=256)),
                ('phone', saleor.account.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, region=None)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='wmsdocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_created_by', to='account.user'),
        ),
        migrations.AlterField(
            model_name='wmsdocument',
            name='recipient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='wms_recipient', to='account.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wmsdocument',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_deliverer', to='wms.wmsdeliverer'),
        ),
    ]
