# Generated by Django 3.2.12 on 2022-05-05 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0126_alter_order_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0002_auto_20210707_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsdocument',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
        migrations.AddField(
            model_name='wmsdocument',
            name='recipient_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='wmsdocument',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wmsdocument',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_created_by', to='account.user'),
        ),
    ]
