# Generated by Django 3.1.2 on 2021-06-18 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_auto_20200714_0539'),
        ('wms', '0002_auto_20210617_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmsdocument',
            name='document_type',
            field=models.CharField(choices=[('GRN', 'Goods_received_note'), ('GIN', 'Goods_issued_note'), ('IWM', 'Internal warehouse movement'), ('FGTN', 'Finished goods transfer note'), ('IO', 'Internal outgoings')], max_length=10),
        ),
        migrations.AlterField(
            model_name='wmsdocument',
            name='number',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wmsdocument',
            name='warehouse_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='warehouse.warehouse'),
        ),
    ]
