# Generated by Django 3.1.2 on 2021-07-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_auto_20210618_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wmsdocument',
            options={'permissions': (('manage_wms', 'Manage wms.'),)},
        ),
    ]
