# Generated by Django 3.2.6 on 2021-09-07 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0115_alter_order_language_code'),
        ('order', '0115_merge_20210820_1454'),
    ]

    operations = [
    ]
