# Generated by Django 3.2.12 on 2022-04-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_alter_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='vat_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
