# Generated by Django 3.1.2 on 2021-06-09 14:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0011_auto_20200714_0539'),
        ('product', '0131_update_ts_vector_existing_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WMSDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='data')),
                ('documentType', models.CharField(choices=[('GRN', 'Goods_received_note'), ('GIN', 'Goods_issued_note')], default='GRN', max_length=5)),
                ('deliverer', models.JSONField(blank=True, null=True, verbose_name='Dostawca')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Nr dokumentu')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to=settings.AUTH_USER_MODEL, verbose_name='Kontrahent')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Stworzone przez')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WMSDocumentPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Liczba')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dokument', to='salingo_warehouse.wmsdocument')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_variant', to='product.productvariant')),
            ],
        ),
    ]
